### ISSUE TITLE
Update Pricing

### ISSUE THREAD

**Issue by codytwinton** [truecodersio/truecoders.io#26]
# Story

As a student, I want to know my pricing and financing options for taking a TrueCoders course. I also want to know if I can get a scholarship.

# Tasks

## Course Pricing

- [x] 10K for Course
- [x] Can Apply for Scholarship
- [x] Pay up front and get 10% off
- [ ] Add Financing Details
- [ ] 2.5K first two weeks
- [ ] 2.5K second two weeks
- [ ] 5K last four weeks

## FAQs

- [ ] Update Relevant FAQs
- [ ] Reference this: [Dropbox Paper](https://paper.dropbox.com/doc/TrueCoders-Brochure-k0x30c3OzwXZGRsMxivtu)

**Comment by codytwinton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Pricing](https://trello.com/c/aQ45QUYU/3-update-pricing)

**Comment by codytwinton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Pricing](https://trello.com/c/aQ45QUYU/3-update-pricing)
